### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by CHBMB**
Hi Phil, thanks for that, I've updated the links to point to the docker hub site as that's where the images are pulled from.

If you need anything else from us, let us know.

Neil

### CODE REVIEW

**Comment by philborman** [comment]
Hi,
Hope you're the right person to contact about build changes for the
lazylibrarian docker package. If not, let me know.

Just a quick heads-up, the next version of lazylibrarian needs an extra
library. To read magazines in .cbr format we need the libunrar.so library.
If it's not installed we just print a warning message, its not fatal. As
the library is architecture dependant I dont include it with lazylibrarian.

The unrar library sources are here   http://www.rarlab.com/rar_add.htm
Building it is just  make lib ; sudo make install-lib ; ldconfig
That puts libunrar.so into /usr/lib where we can find it

Thanks

**Comment by CHBMB** [comment]
Hi Phil, 

@sparklyballs has done this.

https://github.com/linuxserver/docker-lazylibrarian/commit/5743f1d32f0490f4f3c1179c2e98a90327b50523
https://github.com/linuxserver/docker-lazylibrarian-armhf/commit/a5266b9b1719b6d968479e3731326c94a48537ee

Should be good to go.

ATB 

Neil

**Comment by philborman** [comment]
Many thanks, that was quick work.

Another user wants to create an unRAID plugin of lazylibrarian, but needs a
list of dependencies that lazylibrarian uses, preferably with minimum
version numbers. I have no idea how to create the list, but presumably
docker needs to know too?
Is there a list somewhere in the docker build instructions?

Kind regards,
Phil.

**Comment by CHBMB** [comment]
He can take a look at the Dockerfile for the LazyLibrarian docker and the Dockerfile for the base image, it's using Alpine Linux, so that should cover all the dependencies.  

Who's the user?  Bet I know them! :)

**Comment by philborman** [comment]
Username is ziggyke <https://github.com/ziggyke>
It reads like a fairly novice programmer (that's rich, coming from me!) but
I will pass on your suggestion and see if that's enough info.

Thanks.

**Pull request merged**
